
[env]
TERM = "xterm-256color"

[window]
# padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 1
blur = true
option_as_alt = "both"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 16

[general]
import = [
  "~/.config/alacritty/themes/tokyonight_night.toml"
]

